### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/julia-for-hpda#1]
- https://github.com/ivanslapnicar/Data-Clustering-in-Julia.jl
- https://juliadatascience.io/
- https://datasciencejuliahackers.com/
- Bobomil Kaminski's "Julia for Data Science" book
- https://github.com/bkamins/JuliaForDataAnalysis
- JuliaDB.jl
- https://github.com/pszufe/MIT_18.S097_Introduction-to-Julia-for-Data-Science

**Comment by fomalhautn** [comment]
These resources were added to motivation and some of them to DS lesson.
