### ISSUE TITLE
style and symbols

### ISSUE THREAD

**Issue by davideklund** [ENCCS/julia-for-hpda#11]
In the introduction text, emojis for type along, important info and so on are referenced. With the style used at the moment, these emojis are replaces by other symbols. Have we decided on a style to use? We should sync the text and the rendering.

**Comment by fomalhautn** [comment]
It is done. Please check the latest commit.

**Comment by davideklund** [comment]
There is still some mismatch in the introduction. 

Exercises are introduced talking about "hand writing emoji" but there is an exclamation mark in the example. The example is "exercise" environment rather than "todo" as in other places.

In important information section  "exclamation mark" is mentioned but it is a bell in the example.

**Comment by fomalhautn** [comment]
@davideklund I updated it with correct info. Thanks.
Dataframes lesson includes all the necessary sections.
<img width="645" alt="Screenshot 2023-09-27 at 17 55 32" src="https://github.com/ENCCS/julia-for-hpda/assets/79667606/466c9f86-8ecc-4bc9-ab3f-8ff52bf0e390">
<img width="880" alt="Screenshot 2023-09-27 at 17 55 38" src="https://github.com/ENCCS/julia-for-hpda/assets/79667606/7a35ae62-ea60-408d-bb72-ea40384329ab">
<img width="888" alt="Screenshot 2023-09-27 at 17 55 47" src="https://github.com/ENCCS/julia-for-hpda/assets/79667606/504eec1c-00d5-4c5d-898f-428f7a42f752">

Does the guide.rst look ok?
Feel free to update it with better formulations.
