### ISSUE TITLE
setup episode needs to be updated

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/julia-for-hpda#5]
especially https://enccs.github.io/julia-for-hpda/setup/#installing-packages and https://enccs.github.io/julia-for-hpda/setup/#configuring-mpi and https://enccs.github.io/julia-for-hpda/setup/#using-eurohpc-systems

**Comment by davideklund** [comment]
Have updated the package list. Will refine it a bit later.

Removed the rest. Including MPI and EUROHPC sections.
