### ISSUE TITLE
adding packages

### ISSUE THREAD

**Issue by davideklund** [ENCCS/julia-for-hpda#9]
What happens when you open julia REPL with specified Project.toml-file 

   $ julia --project=/path/to/Project.toml

and then add packages with add packagename? I guess they are added to the Project.toml file.

**Comment by wikfeldt** [comment]
yes the packages are added to the Project.toml file. There's always some Project.toml that gets updated. If one starts julia without `--project` then it's the default environment Project.toml under `$HOME/.julia`

**Comment by davideklund** [comment]
Ok, great! Then I think the section on Installing packages makes sense (we recall briefly how to do it manually).
